function [eegs_dir, annots_dir, eeg_files] = physio_patients_ls()
    
    eegs_dir = "C:/Users/HFO/Documents/Postdoc_Calgary/Research/Tatsuya/PhysioEEGs/Anonymized_EDFs/HFOHealthy1monto2yrs/";
    annots_dir = "C:/Users/HFO/Documents/Postdoc_Calgary/Research/Tatsuya/PhysioEEGs/Anonymized_EDFs/Elpi_Files/HFOHealthy1monto2yrs/";
    eeg_files = {
        "Physio_Pat_105.edf";...
        "Physio_Pat_106.edf";...
        "Physio_Pat_107.edf";...
        "Physio_Pat_108.edf";...
        "Physio_Pat_109.edf";...
        "Physio_Pat_110.edf";...
        "Physio_Pat_111.edf";...
        "Physio_Pat_112.edf";...
        "Physio_Pat_113.edf";...
        "Physio_Pat_114.edf";...
        "Physio_Pat_115.edf";...
        "Physio_Pat_116.edf";...
        "Physio_Pat_117.edf";...
        "Physio_Pat_118.edf";...
        "Physio_Pat_119.edf";...
        "Physio_Pat_120.edf";...
        "Physio_Pat_121.edf";...
        "Physio_Pat_122.edf";...
        "Physio_Pat_123.edf";...
        "Physio_Pat_124.edf";...
        "Physio_Pat_125.edf";...
        "Physio_Pat_126.edf";...
        "Physio_Pat_127.edf";...
        "Physio_Pat_128.edf";...
        "Physio_Pat_129.edf";...
        "Physio_Pat_130.edf";...
        "Physio_Pat_131.edf";...
        "Physio_Pat_132.edf";...
        "Physio_Pat_133.edf";...
        "Physio_Pat_134.edf";...
        "Physio_Pat_135.edf";...
        "Physio_Pat_136.edf";...
        "Physio_Pat_137.edf";...
        "Physio_Pat_138.edf";...
        "Physio_Pat_139.edf";...
        "Physio_Pat_140.edf";...
        "Physio_Pat_141.edf";...
        "Physio_Pat_142.edf";...
        "Physio_Pat_143.edf";...
        "Physio_Pat_144.edf";...
        "Physio_Pat_145.edf";...
        "Physio_Pat_146.edf";...
        "Physio_Pat_147.edf";...
        "Physio_Pat_148.edf";...
        "Physio_Pat_149.edf";...
        "Physio_Pat_150.edf";...
        "Physio_Pat_151.edf";...
        "Physio_Pat_152.edf";...
        "Physio_Pat_153.edf";...
        "Physio_Pat_154.edf";...
        "Physio_Pat_103.edf";...
        "Physio_Pat_104.edf";...
    };
end

